-- 코드를 입력하세요
SELECT MEMBER_NAME,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") FROM MEMBER_PROFILE S1
INNER JOIN
(
SELECT T1.MEMBER_ID,T1.REVIEW_TEXT,T1.REVIEW_DATE FROM REST_REVIEW T1
INNER JOIN
(SELECT U1.MEMBER_ID, COUNT(*) AS REVIEW_COUNT
FROM REST_REVIEW U1
GROUP BY U1.MEMBER_ID 
HAVING REVIEW_COUNT = (
    SELECT MAX(REVIEW_COUNT)
    FROM (
        SELECT COUNT(*) AS REVIEW_COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) U2
)) T2
WHERE T1.MEMBER_ID = T2.MEMBER_ID) S2
WHERE S1.MEMBER_ID = S2.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT
