-- 코드를 입력하세요

SELECT INGREDIENT_TYPE,SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM FIRST_HALF T1 
      INNER JOIN ICECREAM_INFO T2 ON T1.FLAVOR=T2.FLAVOR 
      AND T2.INGREDIENT_TYPE="sugar_based"
UNION SELECT INGREDIENT_TYPE,SUM(TOTAL_ORDER) AS TOTAL_ORDER 
   FROM FIRST_HALF T1 INNER JOIN ICECREAM_INFO T2 ON T1.FLAVOR=T2.FLAVOR 
   AND T2.INGREDIENT_TYPE="fruit_based"

